# /etc/logrotate.d/cryptobot
/Users/ruiwang/Desktop/bian/logs/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    create 0644 ruiwang staff
    dateext
    dateformat -%Y%m%d
}
